### PR TITLE
Ft 1game logic

### PR DESCRIPTION
**Pull request by Grifo89**

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

Hi Grifo89!

I can see you implemented this project alone - solo. However, it is mean't to be a collaborative project. I believe you have your good reasons, kindly let us know by leaving a comment :slightly_smiling_face: 

Everything looks fine, referring to the [request](https://github.com/Grifo89/ruby-tic-tac-toe/pull/4#pullrequestreview-315071068) from my colleague. 

But I won't be approving the project :slightly_smiling_face:  

There is conflict to resolve :point_down: 

After fixing the conflict submit another form for a code review.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Comment by Grifo89** [comment]
Hey guys! come on the project is okay and I was allowed to submit it alone by Willow.

**Review by whiz25 — CHANGES_REQUESTED** [review]
### Hey @Grifo89 
Please fix the conflict as suggested by the previous reviewer and submit for another review.

### Martin Afani

**Comment by Grifo89** [comment]
Hey, @whiz25 may I ask you a question? did you even bother to read the pull request history and also check if the code works?

**Comment by whiz25** [comment]
Hey sorry for the inconvenience caused by my review. Your code works well, I tested it.
However, I could not approve it because you had conflicts in your code which needed to fixed as you already know.
Please fix the conflicts if they are still there and resubmit for another review.
My apologies once again.

**Review by stratospherique — APPROVED** [review]
### Great work implementing the suggested changes :clap: :clap: This milestone is approved :heavy_check_mark: and you may merge and pass to the next :+1: :+1: :+1: 

Keep up the good work :muscle: 
_**Ahmed Mahfoudh**_

**Comment by Grifo89** [comment]
Thank you @stratospherique !

**Pull request merged**
