### PR TITLE
First Pull Request Milestone #4 ruby project

### PR DESCRIPTION
**Pull request by Grifo89**
Hey guys, I'm ready to have a review. Thanks

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Good implementation :+1: 
Nice try with the milestone. This PR is not ready for merge yet. You have some bugs in your code that need fixing.
bug2

#### Please fix that and submit for another review.
### Martin Afani

**Comment by Grifo89** [comment]
Hey, @whiz25 something should be wrong with your clone or in your console because for me it is working like charm.

image

**Review by wathigo — CHANGES_REQUESTED** [review]
## Changes Required :smile: 

The game is executing properly.
Let's address this issue before we move on:
* Let's terminate the game immediately when the player wins. In our case the second user is still prompted to choose a position before declaring the winner. See this :point_down:  
tic

### [OPTIONAL]
* We can add a play again functionality after a win or a draw.

**After implementing the changes, submit another request for review.**

Feel free to reach out via slack for any clarification or issue.

_Happy Coding :computer:  
Reviewed by: **Simon Wathigo**_

**Comment by Grifo89** [comment]
The change is done.

**Pull request closed without merging**
